services:
  app:
    build: ./
    ports:
      - "8000:5000"
    env_file:
      - secrets/appid.env
      - secrets/database_url.env
    depends_on:
      - db

  db:
      image: postgres:15.4
      environment:
        POSTGRES_DB: flask_app_db
      volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      env_file:
        - secrets/database_user.env
        - secrets/database_password.env
